"""empty message

Revision ID: 50b76870a7c2
Revises: 81013dd985de
Create Date: 2017-10-23 10:27:49.304000

"""

# revision identifiers, used by Alembic.
revision = '50b76870a7c2'
down_revision = '81013dd985de'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('real_name', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'real_name')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'address')
    ### end Alembic commands ###
