"""empty message

Revision ID: 7bc09a268523
Revises: c6686e4de00c
Create Date: 2017-10-28 16:27:04.096000

"""

# revision identifiers, used by Alembic.
revision = '7bc09a268523'
down_revision = 'c6686e4de00c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_auth', sa.Integer(), nullable=False))
    op.drop_column('users', 'is_authenticated')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_authenticated', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('users', 'is_auth')
    ### end Alembic commands ###
