"""empty message

Revision ID: 8294b00f5265
Revises: 2da0755a67e5
Create Date: 2017-11-04 10:42:18.880000

"""

# revision identifiers, used by Alembic.
revision = '8294b00f5265'
down_revision = '2da0755a67e5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('visitNum', sa.Integer(), nullable=True),
    sa.Column('updatedTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column(u'news', 'poster',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'news', 'poster',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.drop_table('notices')
    ### end Alembic commands ###
