"""empty message

Revision ID: c6686e4de00c
Revises: 50b76870a7c2
Create Date: 2017-10-28 16:05:38.317000

"""

# revision identifiers, used by Alembic.
revision = 'c6686e4de00c'
down_revision = '50b76870a7c2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_authenticated', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_authenticated')
    ### end Alembic commands ###
